before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: kgIjrMCSDn4WX0bQjL1AL0KDZvEYQe/v0rZoeGKWOpMjIZI5f+AAGtSWI7oPC2XVyOX4HusPprY6hHNhOfW0HDAquW/3IbfkZLdIUyHkrxFFy7gQ6dM9761cNQD5bGA9Sx/TVSbmxb88VsvR9PkvGSi6b8TnXBymecWxEYJZDlgCjfCKR1HHjcm7r4rn0ygV+zPVaVkzPRNRvYnm+2cw2fK6t3zk+bPPpE6WPxuVGb1CkuEB7ow9HnnFbgpC3ZWuOl4rVUJQqcusABR9EywjMPFG73YfWz0REuenUohJQ4zpMMbA34JLBnjo+IUY4gXhR4+u4MPXCSw5UisJcTI66+Ur1dKUFLwgU1hS9b5Qmq2ThdB9TdZBVNXZDx3grNEAtcVA/46HHjCMcr2srCG1+Oc4yniMpgQilVyi7HSSHiRAIw5qxpTC+Gd0pF45kCq75sBsDKyO2pHcyGjTH1IyYkdATmnyCPpgM664LOmWMBQb9xJLqnNwiv0CmtagPnNdlO8Cq7PIqvT4xB+tUKbnq9RuZKZDVk6zTF5U0NVm4TuZOaUy0KjW58xUd0eO2/v792ZIigw3ScMc/64V6UYiwHePVmMHGyFG+oSMCOcvuyNCy0jYfKrP7TI6EcJgBgvvCXd4SLe72hL541xb5JwjZY3bsFTMHrHKslrM63eIcFQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
